### ISSUE TITLE
vagrant-docker-nsenter and non-docker providers

### ISSUE THREAD

**Issue by jperville** [smerrill/vagrant-docker-nsenter#1]
I tried the plugin to see if I can nsenter into a docker container that is running within a virtualbox vagrant VM (it is not using the docker provider). The nsenter command is already installed in the proxy virtual machine.

I get the following error:

```
$ vagrant docker-nsenter --no-interactive -- hostname
An active machine was found with a different provider. Vagrant
currently allows each machine to be brought up with only a single
provider at a time. A future version will remove this limitation.
Until then, please destroy the existing machine to up with a new
provider.

Machine name: default
Active provider: virtualbox
Requested provider: docker
```

I'm very unfamiliar with vagrant plugins, but I don't think much is missing to make it compatible with other providers than the docker one.

**Comment by phpguru** [comment]
I'm getting this also. Until @smerrill gives insight, here is the 2-step workaround I've been using:

```
host-os:$ vagrant ssh
                    ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.4.1, build yungsang/boot2docker : 7683f7c - Sat Dec 20 05:05:14 UTC 2014
Docker version 1.4.1, build 5bc2ff8
docker@boot2docker:~$ docker-enter container-name
```

Also, if you 

```
docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
```

then you can use this in your ~/.bash_profile

```
docker-enter() {
  vagrant ssh -c "/var/lib/boot2docker/docker-enter $@"
}
```

Then `docker-enter container-name` works with a non-docker Vagrant box as it does with the native boot2docker implementation.

**Comment by smerrill** [comment]
Honestly, now that `docker exec` is a capability of Docker 1.3.x+, I will likely deprecate this plugin soon. If you point your DOCKER_HOST properly, you can `docker exec -it $CONTAINER_NAME_OR_ID bash` and get a shell (or replace bash to run a command.)
